fix: configure webpackHotDevClient properly
We’ve been seeing errors in MFEs using frontend-build 5.6.10 where they were unable to connect to webpack-dev-server for hot reloading, and it was making the server shut down.

The server would error out with:

events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}

And the client would error out with a message like:

WebSocket connection to 'ws://localhost:8735/sockjs-node' failed:

The fix was to set transportMode to ‘ws’ in our webpack config.  I also added some comments straight out of react-scripts to what the `hot` value means, since it seemed helpful.